//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace card
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_current
    {
        public int id { get; set; }
        public Nullable<int> row { get; set; }
        public string name { get; set; }
        public string side { get; set; }
        public string field_main { get; set; }
        public string field_other { get; set; }
        public string floor { get; set; }
        public string classnumber { get; set; }
        public string v_start { get; set; }
        public string v_end { get; set; }
        public string v_number { get; set; }
        public string picture { get; set; }
    }
}
